### PR TITLE
Post details fix for login

### PR DESCRIPTION
**Pull request by levent91**
Merged 3 different responses to output the same schema as before. I tested with image, carousel, and video posts and they appear to be working. But we definitely need more testing before the release. Obviously, the structure and the code aren't perfect, so there are several to-dos.

### CODE REVIEW

**Review by metalwarrior665 — APPROVED** [review]
Thanks. What is the actual fix? It seems that it just removed the `?` :D Or did I miss something?

**Review by metalwarrior665 — COMMENTED** [review]
@levent91 Sorry, I had a wrong diff loaded. I can see the changes now

**Review by metalwarrior665 — COMMENTED** [review]
Not sure what `asd.json` means. I would create a folder called e.g. response-examples and in this folder a txt file explaining how each file maps to a response URL and what is in the data.

**Comment by levent91** [comment]
Forgot to disclude the test file :facepalm: . Removing.

**Pull request merged**
