### PR TITLE
Make puppeteer more resilient to https & SSL errors

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by AndrewSB** [comment]
potentially related to #19? Will update in that issue with a reduced input for testing

**Comment by metalwarrior665** [comment]
Have you tested this (ideally on a case which was failing before)? It looks pretty safe to merge.

**Comment by AndrewSB** [comment]
yup, this fixed the problem I was running into

**Comment by metalwarrior665** [comment]
Ok, will merge and run in the TEST build for a while. Thanks.

**Pull request merged**
