### PR TITLE
Update input to make proxy optional

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by metalwarrior665** [comment]
One reason proxy is not optional is that people can abuse the solution without proxy and Instagram can report our default IPs. We will think about how to address this differently.

**Comment by AndrewSB** [comment]
that makes total sense - but not having a proxy makes this way easier to test during development

**Comment by metalwarrior665** [comment]
For us, a potential report by Instagram would be a big problem. Maybe we could limit no-proxy to local usage and on-platform only to 5 requests. Would that work for you?

**Comment by metalwarrior665** [comment]
Proxy is now optional outside of Apify platform.

**Pull request closed without merging**
